import type { Metadata } from "next";
import "./globals.css";
import { inter, manrope } from "./fonts";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
          {children}
          <Toaster position="top-center" richColors/>
          <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
